/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Lili
 */
public class DlgCrearProducto extends javax.swing.JDialog {

    /**
     * Creates new form Producto
     */
    public DlgCrearProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CodBarrasProd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_CancProd = new javax.swing.JButton();
        btn_CancProd1 = new javax.swing.JButton();
        btn_EditarProd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt_CodBarrasProd);
        txt_CodBarrasProd.setBounds(60, 40, 280, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 109, 240));
        jLabel13.setText("Buscar");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 40, 50, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Laboratorio", "Presentación", "P. comp", "P. venta", "Nombre"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 70, 680, 110);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btn_CancProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CancProd.setForeground(new java.awt.Color(0, 109, 240));
        btn_CancProd.setText("Editar");
        btn_CancProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancProdActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CancProd);
        btn_CancProd.setBounds(550, 30, 107, 31);

        btn_CancProd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CancProd1.setForeground(new java.awt.Color(0, 109, 240));
        btn_CancProd1.setText("Aceptar");
        btn_CancProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancProd1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CancProd1);
        btn_CancProd1.setBounds(380, 370, 107, 31);

        btn_EditarProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_EditarProd.setForeground(new java.awt.Color(0, 109, 240));
        btn_EditarProd.setText("Salir");
        btn_EditarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarProdActionPerformed(evt);
            }
        });
        jPanel2.add(btn_EditarProd);
        btn_EditarProd.setBounds(180, 370, 90, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 109, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Producto");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 680, 410);

        setSize(new java.awt.Dimension(693, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancProdActionPerformed

    private void btn_EditarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditarProdActionPerformed

    private void btn_CancProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancProd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancProd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCrearProducto dialog = new DlgCrearProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancProd;
    private javax.swing.JButton btn_CancProd1;
    private javax.swing.JButton btn_EditarProd;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_CodBarrasProd;
    // End of variables declaration//GEN-END:variables
}
