/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Lili
 */
public class DlgEgresos extends javax.swing.JDialog {

    /**
     * Creates new form Egresos
     */
    public DlgEgresos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_BenefEg = new javax.swing.JTextField();
        txt_CantProdEg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_CodProdEg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_NombProdEg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ObservEg = new javax.swing.JTextArea();
        btn_EliminarEg = new javax.swing.JButton();
        btn_GuardarEg = new javax.swing.JButton();
        btn_ImprimirEg = new javax.swing.JButton();
        txt_totalEg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_SalirEg = new javax.swing.JButton();
        btn_IngresarEg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Egresos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 40, 70, 30);
        getContentPane().add(txt_BenefEg);
        txt_BenefEg.setBounds(130, 40, 220, 30);
        getContentPane().add(txt_CantProdEg);
        txt_CantProdEg.setBounds(130, 90, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(" Cantidad Producto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 90, 130, 30);
        getContentPane().add(txt_CodProdEg);
        txt_CodProdEg.setBounds(130, 140, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText(" Código Producto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 140, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText(" Nombre Producto:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 190, 130, 30);
        getContentPane().add(txt_NombProdEg);
        txt_NombProdEg.setBounds(130, 190, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText(" Beneficiario:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 40, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Cant", "P.Unit", "P.Total", "P.V.P", "Dsct", "P.V.P - Dsct"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 230, 620, 110);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(430, 40, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Observaciones:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 80, 110, 30);

        txt_ObservEg.setColumns(20);
        txt_ObservEg.setRows(5);
        jScrollPane2.setViewportView(txt_ObservEg);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(380, 110, 240, 60);

        btn_EliminarEg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_EliminarEg.setText("Eliminar");
        getContentPane().add(btn_EliminarEg);
        btn_EliminarEg.setBounds(500, 190, 100, 30);

        btn_GuardarEg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_GuardarEg.setText("Guardar");
        getContentPane().add(btn_GuardarEg);
        btn_GuardarEg.setBounds(20, 360, 95, 30);

        btn_ImprimirEg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ImprimirEg.setText("Imprimir");
        getContentPane().add(btn_ImprimirEg);
        btn_ImprimirEg.setBounds(130, 360, 100, 30);
        getContentPane().add(txt_totalEg);
        txt_totalEg.setBounds(470, 360, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total $:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 360, 60, 30);

        btn_SalirEg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_SalirEg.setText("Salir");
        getContentPane().add(btn_SalirEg);
        btn_SalirEg.setBounds(240, 360, 70, 30);

        btn_IngresarEg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresarEg.setText("Ingresar");
        getContentPane().add(btn_IngresarEg);
        btn_IngresarEg.setBounds(380, 190, 100, 30);

        setSize(new java.awt.Dimension(642, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgEgresos dialog = new DlgEgresos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EliminarEg;
    private javax.swing.JButton btn_GuardarEg;
    private javax.swing.JButton btn_ImprimirEg;
    private javax.swing.JButton btn_IngresarEg;
    private javax.swing.JButton btn_SalirEg;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_BenefEg;
    private javax.swing.JTextField txt_CantProdEg;
    private javax.swing.JTextField txt_CodProdEg;
    private javax.swing.JTextField txt_NombProdEg;
    private javax.swing.JTextArea txt_ObservEg;
    private javax.swing.JTextField txt_totalEg;
    // End of variables declaration//GEN-END:variables
}
