/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Lili
 */
public class DlgListadoProducto extends javax.swing.JDialog {

    /**
     * Creates new form Producto
     */
    public DlgListadoProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_CancProd1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_CancProd2 = new javax.swing.JButton();
        btn_CancProd3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txt_CodBarrasProd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btn_CancProd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CancProd1.setForeground(new java.awt.Color(0, 109, 240));
        btn_CancProd1.setText("Salir");
        btn_CancProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancProd1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CancProd1);
        btn_CancProd1.setBounds(550, 480, 120, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 109, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listado de Producto");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 30);

        btn_CancProd2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CancProd2.setForeground(new java.awt.Color(0, 109, 240));
        btn_CancProd2.setText("Aceptar");
        btn_CancProd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancProd2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CancProd2);
        btn_CancProd2.setBounds(110, 480, 120, 50);

        btn_CancProd3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CancProd3.setForeground(new java.awt.Color(0, 109, 240));
        btn_CancProd3.setText("Editar");
        btn_CancProd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancProd3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_CancProd3);
        btn_CancProd3.setBounds(330, 480, 120, 50);

        jRadioButton1.setText("Laboratorio");
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(560, 40, 120, 23);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Nombre");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(440, 40, 82, 23);
        jPanel2.add(txt_CodBarrasProd);
        txt_CodBarrasProd.setBounds(90, 40, 320, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 109, 240));
        jLabel13.setText("Buscar");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 40, 50, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Laboratorio", "Presentación", "P. comp", "P. venta", "Nombre"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 830, 390);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 540);

        setSize(new java.awt.Dimension(854, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancProd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancProd1ActionPerformed

    private void btn_CancProd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancProd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancProd2ActionPerformed

    private void btn_CancProd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancProd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancProd3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgListadoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgListadoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgListadoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgListadoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgListadoProducto dialog = new DlgListadoProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancProd1;
    private javax.swing.JButton btn_CancProd2;
    private javax.swing.JButton btn_CancProd3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_CodBarrasProd;
    // End of variables declaration//GEN-END:variables
}
