/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.utilidades.UtilidadesComponente;
import controlador.servicio.LaboratorioServicio;
import controlador.servicio.LoteServicio;
import controlador.servicio.PresentacionServicio;
import controlador.servicio.ProductoServicio;
import controlador.utilidades.Utilidades;
import java.util.Date;
import modelo.Laboratorio;
import modelo.Presentacion;
/**
 *
 * @author franzandresflores
 */
public class FrmCompras extends javax.swing.JFrame {
    
    private LoteServicio los = new LoteServicio();
    private ProductoServicio prs = new ProductoServicio();
    
    PresentacionServicio ps = new PresentacionServicio();
    LaboratorioServicio ls = new LaboratorioServicio ();
    
    public FrmCompras() {
        initComponents();
        
    }
    
    private void cargarObjeto(){
//        los.getLote().setNombre(txt_nombre.getText());
//        los.getLote().setCantidad(Integer.parseInt(txt_cantidad.getText()));
//        los.getLote().setFechaFabricacion(date_fabricacion.getDate());
//        los.getLote().setFechaVencimiento(date_vencimiento.getDate());
//        los.getLote().setFechaCompra(new Date());
//        los.getLote().setPrecio_compra(Utilidades.redondearDecimales(Double.parseDouble(txt_precio.getText()),2));
//        los.getLote().setLaboratorio((Laboratorio) cbx_laboratorio.getSelectedItem());
//        los.getLote().setPresentacion((Presentacion) cbx_presentacion.getSelectedItem());
        
        
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_listado = new javax.swing.JButton();
        date_fabricacion = new com.toedter.calendar.JDateChooser();
        date_vencimiento = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txt_precio1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 109, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMPRAS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 920, 40);

        jLabel3.setForeground(new java.awt.Color(0, 109, 240));
        jLabel3.setText("Ced/RUC");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 60, 70, 20);
        jPanel1.add(txt_cedula);
        txt_cedula.setBounds(100, 60, 220, 30);

        jLabel4.setForeground(new java.awt.Color(0, 109, 240));
        jLabel4.setText("Proveedor");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 100, 70, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 100, 360, 30);

        jLabel5.setForeground(new java.awt.Color(0, 109, 240));
        jLabel5.setText("Dirección ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 64, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(100, 140, 360, 30);

        jLabel6.setForeground(new java.awt.Color(0, 109, 240));
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 180, 55, 20);

        btn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/usuario.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar);
        btn_agregar.setBounds(340, 50, 50, 40);

        btn_listado.setBackground(new java.awt.Color(255, 255, 255));
        btn_listado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/usuarios.png"))); // NOI18N
        btn_listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_listado);
        btn_listado.setBounds(400, 50, 50, 40);
        jPanel1.add(date_fabricacion);
        date_fabricacion.setBounds(600, 100, 190, 30);
        jPanel1.add(date_vencimiento);
        date_vencimiento.setBounds(600, 140, 190, 30);

        jLabel9.setForeground(new java.awt.Color(0, 109, 240));
        jLabel9.setText("Fecha Fabricación");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(480, 100, 140, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(100, 180, 360, 30);

        jPanel2.setBackground(new java.awt.Color(56, 146, 255));
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Detalle");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(100, 10, 50, 20);
        jPanel2.add(txt_nombre);
        txt_nombre.setBounds(90, 30, 420, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Costo");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(530, 10, 60, 20);
        jPanel2.add(txt_precio);
        txt_precio.setBounds(530, 30, 90, 30);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cant");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(650, 10, 60, 20);
        jPanel2.add(txt_cantidad);
        txt_cantidad.setBounds(650, 30, 60, 30);

        btn_ingresar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(0, 109, 240));
        btn_ingresar.setText("Ingresar");
        jPanel2.add(btn_ingresar);
        btn_ingresar.setBounds(740, 20, 90, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 820, 260);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Código");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 10, 60, 20);
        jPanel2.add(txt_precio1);
        txt_precio1.setBounds(10, 30, 70, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 220, 850, 340);

        jLabel11.setForeground(new java.awt.Color(0, 109, 240));
        jLabel11.setText("Fecha Vencimiento");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 140, 140, 20);

        btn_cancelar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 109, 240));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar);
        btn_cancelar.setBounds(560, 570, 110, 40);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 109, 240));
        jButton5.setText("ACEPTAR");
        jPanel1.add(jButton5);
        jButton5.setBounds(240, 570, 110, 40);

        jLabel7.setForeground(new java.awt.Color(0, 109, 240));
        jLabel7.setText("Lote");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 180, 27, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(550, 180, 240, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 620);

        setSize(new java.awt.Dimension(878, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listadoActionPerformed
        // TODO add your handling code here:
        new DlgListaCliente().setVisible(true);
    }//GEN-LAST:event_btn_listadoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_listado;
    private com.toedter.calendar.JDateChooser date_fabricacion;
    private com.toedter.calendar.JDateChooser date_vencimiento;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_precio1;
    // End of variables declaration//GEN-END:variables
}
