/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.DetalleServicio;
import controlador.servicio.FacturaServicio;
import controlador.servicio.LoteServicio;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.util.List;
import modelo.Detalle;
import modelo.Lote;
import modelo.Producto;
import vista.DlgListaProductos;
import vista.tablas.ModeloVistaDetalle;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author franzandresflores
 */
public class FrmDetalle extends javax.swing.JFrame {

    private final DlgListaProductos producto = new DlgListaProductos(this, true);
    private ModeloVistaDetalle modelo = new ModeloVistaDetalle();

    private LoteServicio ls = new LoteServicio();
    private DetalleServicio ds = new DetalleServicio();
    private FacturaServicio fs;

    public FrmDetalle() {
        this.fs = new FacturaServicio();
        initComponents();
        presionadoProducto();
        limpiar();
    }

    private void limpiar() {
        txt_cantidad.setText("");
        txt_codigo.setText("");
        txt_detalle.setText("");
        cargarTabla();
    }
    
    private void presionadoProducto() {
        btn_lista.addActionListener((ActionEvent arg0) -> {
            if (arg0.getSource().equals(btn_lista)) {
                cargarProducto();
            }
        });
    }

    private Producto cargarProducto() {
        if (producto.escogerItem() != null) {
            txt_detalle.setText(producto.escogerItem().getNombre());
            txt_codigo.setText(producto.escogerItem().getCodigo());
            return producto.escogerItem();
        }
        return null;
    }
  
    private void cargarTabla() {
        modelo.setLista(ds.todos());
        tbl_tabla.setModel(modelo);
        tbl_tabla.updateUI();
    }



    private Integer cantidad() {
        return Integer.parseInt(txt_cantidad.getText());
    }
        
    private Lote lote() {
        return ls.restarStock(producto.escogerItem().getCodigo(), cantidad());
    }

    private void cargarObjeto() {
        ds.getDetalle().setCantidad(cantidad());
        ds.getDetalle().setLote(lote());
        ds.getDetalle().setFactura(fs.getFactura());
    }

    private Detalle obtenerDetalle() {
        ds.getDetalle().setCantidad(cantidad());
        ds.getDetalle().setLote(lote());
        ds.getDetalle().setFactura(fs.getFactura());
        return ds.getDetalle();
    }

    public List<Detalle> listaDetalle() {
        List<Detalle> lista = null;
        lista.add(obtenerDetalle());
        return lista;
    }

    private void guardar() {
        String mensaje = "Campo requerido";
        if (!UtilidadesComponente.mostrarError(txt_codigo, mensaje, 'r')) {
            
            if (ds.getDetalle().getId() == null) {
                if (ds.guardar()) {
                    UtilidadesComponente.mensajeOk("OK", "Se ha registrado correctamente");
                    limpiar();
                } else {
                    UtilidadesComponente.mensajeError("ERROR", "No se pudo guardar");
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_lista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        txt_codigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_detalle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_ingresar1 = new javax.swing.JButton();
        btn_aceptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 109, 240)));
        jPanel2.setForeground(new java.awt.Color(0, 109, 240));
        jPanel2.setLayout(null);

        btn_lista.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_lista.setForeground(new java.awt.Color(0, 109, 240));
        btn_lista.setText("Ver Lista");
        btn_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_lista);
        btn_lista.setBounds(510, 50, 90, 40);

        tbl_tabla.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tbl_tabla);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 650, 320);

        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_codigo);
        txt_codigo.setBounds(30, 70, 60, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 109, 240));
        jLabel9.setText("Cant");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(430, 50, 40, 16);

        txt_detalle.setEditable(false);
        jPanel2.add(txt_detalle);
        txt_detalle.setBounds(90, 70, 320, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 109, 240));
        jLabel8.setText("Descripción");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 50, 80, 16);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 109, 240));
        jLabel7.setText("Código");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 50, 45, 20);

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txt_cantidad);
        txt_cantidad.setBounds(420, 70, 70, 30);

        btn_aceptar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(0, 109, 240));
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_aceptar);
        btn_aceptar.setBounds(370, 440, 90, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 109, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalle");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 50);

        btn_ingresar1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_ingresar1.setForeground(new java.awt.Color(0, 109, 240));
        btn_ingresar1.setText("Ingresar");
        btn_ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ingresar1);
        btn_ingresar1.setBounds(600, 50, 90, 40);

        btn_aceptar1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_aceptar1.setForeground(new java.awt.Color(0, 109, 240));
        btn_aceptar1.setText("Aceptar");
        btn_aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_aceptar1);
        btn_aceptar1.setBounds(210, 440, 90, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 490);

        setBounds(0, 0, 711, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaActionPerformed
        // TODO add your handling code here:
        producto.setVisible(true);
    }//GEN-LAST:event_btn_listaActionPerformed

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_codigoKeyTyped

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar1ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btn_ingresar1ActionPerformed

    private void btn_aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_aceptar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_aceptar1;
    private javax.swing.JButton btn_ingresar1;
    private javax.swing.JButton btn_lista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tabla;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_detalle;
    // End of variables declaration//GEN-END:variables
}
