/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.utilidades.UtilidadesComponente;
import controlador.servicio.LaboratorioServicio;
import controlador.servicio.LoteServicio;
import controlador.servicio.PresentacionServicio;
import controlador.servicio.ProductoServicio;
import controlador.utilidades.Utilidades;
import java.util.Date;
import modelo.Laboratorio;
import modelo.Presentacion;
/**
 *
 * @author franzandresflores
 */
public class FrmProducto extends javax.swing.JFrame {
    
    private LoteServicio los = new LoteServicio();
    private ProductoServicio prs = new ProductoServicio();
    
    PresentacionServicio ps = new PresentacionServicio();
    LaboratorioServicio ls = new LaboratorioServicio ();
    
    public FrmProducto() {
        initComponents();
        cargarCombos();
    }
    
    
    private void cargarObjeto(){
//        los.getLote().setNombre(txt_nombre.getText());
//        los.getLote().setCantidad(Integer.parseInt(txt_cantidad.getText()));
//        los.getLote().setFechaFabricacion(date_fabricacion.getDate());
//        los.getLote().setFechaVencimiento(date_vencimiento.getDate());
//        los.getLote().setFechaCompra(new Date());
//        los.getLote().setPrecio_compra(Utilidades.redondearDecimales(Double.parseDouble(txt_precio.getText()),2));
//        los.getLote().setLaboratorio((Laboratorio) cbx_laboratorio.getSelectedItem());
//        los.getLote().setPresentacion((Presentacion) cbx_presentacion.getSelectedItem());
        
        
    }
    
    private void cargarCombos() {
        UtilidadesComponente.llenarComboPresentacion(ps,cbx_presentacion);
        cbx_presentacion.updateUI();
        UtilidadesComponente.llenarComboLaboratorio(ls,cbx_laboratorio);
        cbx_laboratorio.updateUI();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbx_laboratorio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbx_presentacion = new javax.swing.JComboBox<>();
        btn_cancelar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_laboratorio = new javax.swing.JButton();
        btn_presentacion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 109, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresar Producto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 40);

        jLabel7.setForeground(new java.awt.Color(0, 109, 240));
        jLabel7.setText("Laboratorio");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 180, 80, 20);

        cbx_laboratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbx_laboratorio);
        cbx_laboratorio.setBounds(110, 180, 180, 30);

        jLabel10.setForeground(new java.awt.Color(0, 109, 240));
        jLabel10.setText("Presentación");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 140, 80, 20);

        cbx_presentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbx_presentacion);
        cbx_presentacion.setBounds(110, 140, 180, 30);

        btn_cancelar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 109, 240));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar);
        btn_cancelar.setBounds(210, 400, 110, 40);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 109, 240));
        jButton5.setText("ACEPTAR");
        jPanel1.add(jButton5);
        jButton5.setBounds(50, 400, 110, 40);

        btn_laboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Copia de mas.png"))); // NOI18N
        btn_laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laboratorioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laboratorio);
        btn_laboratorio.setBounds(300, 180, 30, 30);

        btn_presentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Copia de mas.png"))); // NOI18N
        btn_presentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_presentacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_presentacion);
        btn_presentacion.setBounds(300, 140, 30, 30);

        jLabel5.setForeground(new java.awt.Color(0, 109, 240));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 70, 20);

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 50, 70, 30);

        jLabel6.setForeground(new java.awt.Color(0, 109, 240));
        jLabel6.setText("Costo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 230, 100, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(70, 230, 120, 30);

        jLabel8.setForeground(new java.awt.Color(0, 109, 240));
        jLabel8.setText("P.V.P");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 330, 80, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(280, 230, 80, 30);

        jLabel9.setForeground(new java.awt.Color(0, 109, 240));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("IVA");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 230, 80, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(70, 280, 120, 30);

        jLabel11.setForeground(new java.awt.Color(0, 109, 240));
        jLabel11.setText("Desc.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 280, 35, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(280, 280, 80, 30);

        jLabel12.setForeground(new java.awt.Color(0, 109, 240));
        jLabel12.setText("Código");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 56, 50, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(110, 90, 250, 30);

        jLabel13.setForeground(new java.awt.Color(0, 109, 240));
        jLabel13.setText("P.V.P-Desc.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(200, 280, 90, 30);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(170, 330, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 470);

        setSize(new java.awt.Dimension(395, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_presentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_presentacionActionPerformed
        // TODO add your handling code here:
        new DlgPresentacion(this,true).setVisible(true);
    }//GEN-LAST:event_btn_presentacionActionPerformed

    private void btn_laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laboratorioActionPerformed
        // TODO add your handling code here:
        new DlgLaboratorio(this,true).setVisible(true);
    }//GEN-LAST:event_btn_laboratorioActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_laboratorio;
    private javax.swing.JButton btn_presentacion;
    private javax.swing.JComboBox<String> cbx_laboratorio;
    private javax.swing.JComboBox<String> cbx_presentacion;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
