/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFrame;

/**
 *
 * @author franzandresflores
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_cliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mn_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mn_factura = new javax.swing.JMenuItem();
        mn_listadoVentas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mn_compras = new javax.swing.JMenuItem();
        mn_listaCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Facturacion");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 23, 1200, 900));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/principal.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 0, 1010, 760);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1380, 830);

        jMenuBar1.setBackground(new java.awt.Color(0, 109, 240));

        jMenu1.setText("General");

        mn_cliente.setText("Cliente");
        jMenu1.add(mn_cliente);

        jMenuItem2.setText("Proveedores");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Usuarios");
        jMenu1.add(jMenuItem3);

        mn_salir.setText("Salir");
        mn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_salirActionPerformed(evt);
            }
        });
        jMenu1.add(mn_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventarios");

        jMenuItem5.setText("Productos");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Crear Producto");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Ingresos -Altas");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Egresos -Bajas");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ventas");

        mn_factura.setText("Crear Factura");
        mn_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_facturaActionPerformed(evt);
            }
        });
        jMenu3.add(mn_factura);

        mn_listadoVentas.setText("Listado de Ventas");
        mn_listadoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_listadoVentasActionPerformed(evt);
            }
        });
        jMenu3.add(mn_listadoVentas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Compras");

        mn_compras.setText("Compras");
        mn_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_comprasActionPerformed(evt);
            }
        });
        jMenu4.add(mn_compras);

        mn_listaCompras.setText("Listado de Compras");
        mn_listaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_listaComprasActionPerformed(evt);
            }
        });
        jMenu4.add(mn_listaCompras);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1349, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mn_salirActionPerformed

    private void mn_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_facturaActionPerformed
        // TODO add your handling code here:
        new FrmFactura().setVisible(true);
        
    }//GEN-LAST:event_mn_facturaActionPerformed

    private void mn_listadoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_listadoVentasActionPerformed
        // TODO add your handling code here:
        new ListaVenta(this,true).setVisible(true);
    }//GEN-LAST:event_mn_listadoVentasActionPerformed

    private void mn_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_comprasActionPerformed
        // TODO add your handling code here:
        new FrmCompras().setVisible(true);
    }//GEN-LAST:event_mn_comprasActionPerformed

    private void mn_listaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_listaComprasActionPerformed
        // TODO add your handling code here:
        new ListaCompras(this,true).setVisible(true);
    }//GEN-LAST:event_mn_listaComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("McWin".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mn_cliente;
    private javax.swing.JMenuItem mn_compras;
    private javax.swing.JMenuItem mn_factura;
    private javax.swing.JMenuItem mn_listaCompras;
    private javax.swing.JMenuItem mn_listadoVentas;
    private javax.swing.JMenuItem mn_salir;
    // End of variables declaration//GEN-END:variables
}
